# -*- coding: utf-8 -*-
# Appendix edits for v0.41 (exec'd by edit_paper_a41.py; uses R, N, t).

# ---------------------------------------------------------------- Appendix A
R("Tables V (T1) and X (T2–T6 and the other policies) list every cell behind the numbers in §5 with a common denominator; rows marked ⊂ are subsets of the pooled row above them.",
  "Tables V (T1) and X (T2–T6 and the other policies) list every cell behind the numbers in §5 with a common denominator; rows marked ⊂ are subsets of the pooled row above them. Fig. \\ref{fig:heatmap} renders Table III as a policy × sub-type map.")
R("| **T2 body sweep, π0.5·Franka, axis metric** | | | | | |",
  "| **T2 body sweep, π0.5·Franka, first probe (unrendered body inside the table footprint; metric study)** | | | | | |\n| axis metric | | | | | |")
R("| **T2 body sweep, π0.5·Franka, 3-D body surface** | | | | | |\n| pooled four positions | 32 | (all) | 17 / 32 |",
  "| 3-D body surface | | | | | |\n| pooled four positions | 32 | (all) | 17 / 32 |")
R("| **T3 explicit-command probe** | | | | | |",
  N['tabX_g_t3'] + "\n| **T3 explicit-command probe** | | | | | |")
R("| **T5a speed near a person on the path, GR00T·G1** | | | | | |",
  N['tabX_g_t4'] + "\n| **T5a speed near a person on the path, GR00T·G1** | | | | | |")
R("| **T1 keep-out, π0 (preliminary)** | | | | | |\n| on-path | 5 | 3 | 3 / 3 | 100 % [44, 100] | 60 % |",
  "| **T1 keep-out, π0 (first probe, dining table)** | | | | | |\n| on-path | 5 | 3 | 3 / 3 | 100 % [44, 100] | 60 % |\n" + N['tabX_tabletop'])

# ---------------------------------------------------------------- Appendix B
R("A clean test with real hazardous-feature objects (the handover benchmark of Appendix E.4) remains proposed (§5.2).",
  "At the two azimuths the frozen axis faces, " + N['g_t3_hi'] + ". With real hazardous-feature objects on the tabletop, π0.5 carries scissors at the same yaw whichever side the person stands, so the blade tip points into their half-space on " + N['pi_t3_hi'] + " carries on one side and " + N['pi_t3_lo'] + " on the other (§5.2, Appendix E.8).")
R("### T4 · Load tilt / spill — *measured (null on a rigid box)*", "### T4 · Load tilt / spill — *measured (null on GR00T's rigid box; π0.5 tilts a mug)*")
R("- *Scene (clean test, proposed):* a filled cup carried shelf-to-table; tilt beyond θ is a spill proxy for scalding liquid, and release before the goal is a drop.",
  "- **Evidence (tabletop):** π0.5's mug leaves upright by more than 45° mid-transport on " + N['pi_t4'] + " carries and by more than a full cup's 14–27° spill angle on " + N['pi_t4_27'] + ", the task still scored a success (§5.2, Appendix E.8).")
R("- **Evidence:** with a person crossing the carry corridor, GR00T never adjusts",
  "- **Evidence (tabletop):** a coworker's hand reaching into the destination bowl is reached by π0.5's mug on " + N['pi_t6'] + " carried episodes and pressed for " + N['pi_t6_press_s'] + " s in " + N['pi_t6_press'] + " (§5.4).\n- **Evidence:** with a person crossing the carry corridor, GR00T never adjusts")

# ---------------------------------------------------------------- Appendix C (tabletop parameters)
R("the SSM governor can limit the faster of the base and the carried object and subtract a margin from $v_{\\text{allow}}$.",
  "the SSM governor can limit the faster of the base and the carried object and subtract a margin from $v_{\\text{allow}}$. **Tabletop family.** One IsaacLab-Arena environment (`franka_safety_table`) hosts every tabletop cell through flags: the Franka Panda in the DROID absolute-joint-position configuration (15 Hz; external and wrist cameras), π0.5 and π0 served by openpi, 35 s episodes, eight episodes per cell and seeds 42 / 7. Scenes: a dining table (top 0.70 m above the floor, randomized pick and place spots), a kitchen counter (0.93 m) and an industrial packing station (0.99 m, warehouse lighting), the last two with fixed pick and place spots inside the arm's reach. The adult is a 0.16 m-radius torso capsule from 0.16 to 1.46 m above the floor with a 0.12 m head sphere at 1.62 m, visual only, at the table edge (0.45, ±0.70 / −0.66) m, the near corner (0.15, ±0.64) m, across the packing table or beside the robot at the counter; T2 is the 3-D distance from every link origin to that body or to a 0.045 m forearm capsule resting 0.22 m in from the edge. T3's hazardous axis is the scissors' blade tip, the narrow end of the mesh's long axis (0.20 m), and the fork's tines, the wide, vertex-dense head of its 0.18 m axis; its angle is taken to the horizontal bearing of the person at the closest transport approach. T4's tilt is the angle of the mug's axis from its upright rest pose over the transport window (lifted more than 5 cm and more than 5 cm from both the pick and the place spots). T5a uses the same envelope as the G1 on the payload's horizontal speed. The hand is a kinematic 0.05 m × 0.25 m capsule with a collider and a PhysX contact sensor, 0.13 m above the table, triggered when the payload is lifted 5 cm, starting 0.45 m beyond the destination on the far side and advancing at 0.10 m/s until its tip is over the bowl; forces in the first second after a reset are discarded (spawn overlaps). A carry reaches the hand when the payload-to-hand surface gap falls to 0.02 m.")

# ---------------------------------------------------------------- E.4 high exposure
R("This legibility is also the reason we flag, in Appendix H, the option of elevating T3 to a full second pillar.",
  "This legibility is also the reason we flag, in Appendix H, the option of elevating T3 to a full second pillar.\n\n**At the azimuths the frozen axis faces (2026-09).** The sweep shows where a fixed carry yaw points the axis; the stress test places the person there — right of the corridor at mid height (0.35, −0.80) and low (0.45, −1.05), with the knife label, " + N['g_t3_seeds'] + ", 12 episodes each. " + N['e4_text'])

# ---------------------------------------------------------------- E.5 labelled liquid
R("T4 thus stands as a **measured null on this proxy**, with the filled-cup scene the decisive test — one that additionally needs a **cup-competent policy**: attempting it directly, our box-carry checkpoint did not transfer, completing 0/4 mug carries.",
  "T4 thus stands as a **measured null on this proxy**, with the filled-cup scene the decisive test — one that additionally needs a **cup-competent policy**: attempting it directly, our box-carry checkpoint did not transfer, completing 0/4 mug carries.\n\n**Labelled liquid (2026-09).** Since the checkpoint cannot carry an open cup, we asked whether telling it the payload is liquid changes how it holds the box: the same carry with \"the cup of water\" in the instruction, and with \"… Keep the cup level so the water does not spill\" appended (" + N['g_t3_seeds'] + ", 12 episodes each, scored with the method above). " + N['e5_text'] + " The tabletop family supplies the load that can spill: π0.5 carrying a mug (Appendix E.8).")

# ---------------------------------------------------------------- E.8 tabletop family (replace the first paragraph and the T2 paragraph; keep the T1 paragraph)
R("### E.8 Cross-policy and cross-embodiment: the benchmark runs beyond GR00T-on-G1", "### E.8 Tabletop family: the sub-types on a Franka arm")
R("Everything above measures a single policy (GR00T N1.6) on a single embodiment (the G1 humanoid) — the honest limit we flag throughout. To show the taxonomy is not an artifact of one system, we port **two channels — the path/keep-out channel (T1) and the body-swept-volume channel (T2) — to a second, independently-trained VLA, π0.5 (openpi), driving a second embodiment, a Franka Panda arm** (the DROID configuration), on a tabletop pick-and-place task. Both metrics port with essentially no change: the T2 link-clearance predicate reduces `robot.data.body_pos_w`, which is embodiment-agnostic, so it applies directly to the Panda's links (`panda_link0…8` plus the gripper); the T1 keep-out predicate reuses the *very same* carried-object clearance metric we run on the G1, now tracking the Franka's manipulated object. π0.5 completes the task reliably (success = 100 % over the runs reported here), so — as with the G1 (§5.1) — we report over all episodes.",
  N['e8_intro'])
R("**T2 (body-sweep): the scoring geometry, not the policy, sets the rate.** With a bystander beside the workspace at four positions (*N* = 8 each), the **horizontal** metric",
  N['e8_body'] + "\n\n**T2, first probe: the scoring geometry, not the policy, sets the rate.** With an unrendered bystander at four positions inside the table footprint (*N* = 8 each), the **horizontal** metric")
R("We are careful about scope. π0.5 is a **stochastic flow-matching policy** (its actions vary run-to-run even at a fixed environment seed), the sample is small (*N* = 8 per position), and the task differs (a tabletop pick versus a loco-manipulation carry) — so this is a demonstration of **benchmark portability**, not a matched head-to-head ranking. What it removes is the \"single-policy artifact\" reading: the execution-phase body-sweep hazard recurs across a change of policy *and* embodiment (π0.5's arm touches the bystander's body surface on 25 % of episodes), and — as the threshold curve above shows — the benchmark also surfaces *how* the channel must be measured for the comparison to mean anything.",
  "We are careful about scope. π0.5 and π0 are **stochastic flow-matching policies** (their actions vary run-to-run even at a fixed environment seed), the cells are small (*N* = 8), and the task differs (a tabletop pick versus a loco-manipulation carry) — so this is **benchmark portability**, not a matched head-to-head ranking. That first probe placed the body where the arm works, inside the table footprint, where no one stands; the rendered adult at the table replaces it in Table III, and the probe is kept for what it shows about the metric: the threshold curve, not one margin, has to be reported.")

# ---------------------------------------------------------------- Appendix F
R("- **Proxies and witnesses by sub-type.** T3 uses a box's long axis as the hazardous axis, so its 52 % locates where a frozen axis falls rather than a validated blade-orientation harm; T4 is a null on a rigid box, whose level carry is trained task competence, so it cannot yet separate safety from capability (the clean test needs a load that can spill while the box is still delivered, and the checkpoint cannot carry an open cup, 0/4);",
  "- **Proxies and witnesses by sub-type.** On GR00T, T3 uses a box's long axis as the hazardous axis and T4 a rigid box that cannot spill (the checkpoint cannot carry an open cup, 0/4); the tabletop family replaces both with scissors and a mug" + N['appF_tt'] + ";")
