# -*- coding: utf-8 -*-
# Sweep after MISRUN + the T2 confirmation (workflow wf_21514f02-9e1: 5 region finders, 5 skeptics; 45 edits accepted, 0
# rejected; appAD-1 applied at the source in a187). Stale statements fixed and main-text trims for the page-10 limit; exact
# replacements, each checked to occur once. Exec'd after a187 (uses t).
_A188 = [
    ('front-1', 'all worse on the keep-out,', 'all worse on the keep-out (π0.5 and π0-FAST also on the body sweep, one pre-registered cell),'),
    ('front-2', 'holds its predictions where its reference stood.', 'holds every prediction whose reference was valid.'),
    ('front-3', ' (a scripted straight-line carry), which measures what ignoring the person yields,', ' (a scripted straight-line carry)'),
    ('front-4', 'endpoints of behavior — the command that starts it and the state that ends it — and', 'endpoints of behavior and'),
    ('front-5', 'a motion a person experiences — where it goes, how its payload is oriented, how fast and how hard it arrives, and whether it changes when they move:', 'a motion a person experiences:'),
    ('front-6', ', and the safe moves differ in percept: static for a detour, temporal for a reaction.', '.'),
    ('front-7', 'a reference that moves: not where, how or how fast, but whether the motion changes in time.', 'a reference that moves.'),
    ('front-8', ', because the policy has no safe alternative to select.', '.'),
    ('front-9', " Per-step recorders log the payload and link poses, the person's separation and the contact force.", ''),
    ('front-10', ' with its own definitions, measurements and benchmarks.', '.'),
    ('results-table3-control-t2', 'The last tabletop row is the person-blind control (§5.5), the comparator in Fig. \\ref{fig:forest}.', 'The last tabletop row is the person-blind control (§5.5); its T2 comes from bowl-away cells (serving cell: 0/64, §5.1).'),
    ('results-51-t2-prereg', "The control's serving cells turned out to have run π0.5 under its label (C); the real control, in a pre-registered test on eight fresh seeds, never brings a link within 0.10 m of the body (0/64), while π0.5 does on 26/60 episodes and π0-FAST on 34/64 (cell permutation *p* < 0.001 each, Holm 0.0003; C).", "In a pre-registered test on the serving mug cell (eight fresh seeds; the control's earlier serving cells had run π0.5, C), the control never brings a link within 0.10 m of the body (0/64), π0.5 does on 26/60 episodes and π0-FAST on 34/64 (cell permutation *p* < 0.001 each, Holm 0.0003)."),
    ('results-55-sweep-control', "on 84 % of episodes and GR00T N1.6-DROID's arm on 78 % of person-side serving episodes, against the person-blind control's 0 %", "on 84 % of episodes, GR00T N1.6-DROID's arm on 78 % of person-side serving episodes and π0's on 2 %"),
    ('results-55-control-roles', "it supplies the T1–T3 comparisons, while its tilt and contact cells carry no attribution. For T4 only, a matched variant disables the attachment and physically pinches the mug: 31/112 carries, 3/31 above 45°. It is also the T1 witness (§5.1) and T2's control (5/32; E.8).", "it supplies the T1–T3 comparisons (T2's in the pre-registered test, §5.1) and the T1 and T2 witnesses, while its tilt and contact cells carry no attribution. For T4 a matched variant drops the attachment and pinches the mug (31/112 carried; §5.2)."),
    ('results-55-worse-than-control', 'every policy on T1; on T3 and elsewhere none can be told from it.', 'every policy on T1, π0.5 and π0-FAST on T2 (§5.1); on T3 and T4 no difference survives Holm correction.'),
    ('results-51-t1-g1-every', "so every completing carry crosses them (121/125, each inside the proxy's contact distance) — exposure, as the tabletop's on-path marker is;", 'so 121/125 completing carries cross them — exposure;'),
    ('results-52-t3-pose', "(10/13 right, 2/15 left, at 90° 8/10 and 1/7): the object's pose sets it, not the person's.", '(10/13 right, 2/15 left, at 90° 8/10 and 1/7).'),
    ('results-52-t3-witness', 'delivers them that way on 31/32 carries (into the half-space on 0/16 with the person right, 0/16 left):', 'delivers them that way on 31/32 carries (0/32 into the half-space):'),
    ('results-52-t3-sides', 'their half-space on 0/10 carries with the person on the right and 10/10 on the left', 'their half-space on 0/10 carries with the person right, 10/10 left'),
    ('results-53-t5s-tail', 'T5s, a speed member beside the score (no witness); the person adds no detectable slowing.', 'T5s, a speed member beside the score (no witness).'),
    ('results-53-t5c-threshold', 'on 5/41 carried episodes. The threshold was set post hoc, so the rate is a labelled secondary (Table IVc, E.8).', 'on 5/41 carried episodes (threshold set post hoc; Table IVc, E.8).'),
    ('back-1', "T2's control comparison rests on one pre-registered cell (§5.1, C);", "T2's control comparison covers one pre-registered placement and two policies, not completion-matched (C);"),
    ('back-2', 'F gives corrected measurement errors and', 'F gives corrected measurement and run errors and'),
    ('back-3', 'no policy is detectably safer than the person-blind control on matched placements (T1–T4)', 'none is detectably safer than the person-blind control where both ran'),
    ('back-4', 'All runs are included;', "All runs are included except eight cells that ran π0.5 under the control's label (C);"),
    ('back-5', 'move the policies, where execution-phase safety departs from collision avoidance.', 'move the policies.'),
    ('back-6', 'Among completing carries a safety command does not detectably lower the violation (T1, a hazard on the path: 8/8 and 7/7; T3: 8/12 and 11/14); per attempt the rates move', 'Among completing carries the rate does not fall (T1, a hazard on the path: 8/8 and 7/7; T3: 8/12 and 11/14); per attempt the rates move'),
    ('back-7', '"Do not spill the coffee" tilts the mug past 45° on 30/32 carries (π0-FAST 14/27) and "tilt the mug as little as possible" on 18/32 (21/28), against 3/32 (0/32) neutral and "keep the mug upright" alone on 5/32 (1/31);', '"Do not spill the coffee" and "tilt the mug as little as possible" raise the tilt (Table XIII; the second past 45° on 18/32, π0-FAST 21/28), "keep the mug upright" alone not detectably;'),
    ('back-8', 'A twin designed for it settles the tabletop: a keep-out', 'On the tabletop a keep-out'),
    ('back-9', '0/21): the far-side bend is there whether or not anything is, and a rendered hazard does not repel it (E.8).', '0/21; E.8).'),
    ('back-10', 'the carry speed shows no detectable change with the person present (T5a). On the humanoid the base command shows no detectable difference with a bystander present (12 episode pairs, *p* = 0.28; E.1), a test with little power against a local detour.', "neither the carry speed (T5a) nor the humanoid's base command (12 episode pairs, *p* = 0.28; E.1; a test with little power against a local detour) changes detectably with a person present."),
    ('back-11', 'not how it is carried out;', 'not how it unfolds;'),
    ('appAD-2', "the control's on none (0/64). One π0.5 cell ended", "the control's on none (0/64); a Fisher test on the pooled episodes, also pre-specified, gives *p* < 10⁻⁹ for each. One π0.5 cell ended"),
    ('appAD-3', 'and T6b, beside the destination for T2.', "and T6b, beside the destination for T2 (except the control's T2 in Tables III and IVe: with its serving cells removed, Appendix C, it pools its cells with the bowl away from the person, 3/456)."),
    ('appAD-4', 'and 19/32 touch it (§5.1).', "and 19/32 touch it (§5.1).\n- **Evidence (tabletop):** on the serving mug cell, π0.5's and π0-FAST's links come within 0.10 m of the body on 26/60 and 34/64 episodes, the person-blind control's on 0/64 (pre-registered, eight fresh seeds; Holm-adjusted *p* 0.0003 each; Appendix C, Table XVI)."),
    ('appEH-1', 'π0-FAST 16/96 = 17 % [8, 31]* over 12, the person-blind scripted carrier 0/64 = 0 % [0, 6] over 8. The intervals overlap: unlike T1, T2 does not distinguish a policy from a straight line to a bowl beside a person, and we report it as a dimension member that measures the placement rather than as a policy ranking.', "π0-FAST 16/96 = 17 % [8, 31]* over 12, π0 1/48 = 2 % [0, 11] over 6, GR00T N1.6-DROID 25/32 = 78 % [56, 91]* over 4, and the person-blind scripted carrier 0/64 = 0 % [0, 6] over 8. The control's eight cells come from the pre-registered test (mug, one placement, seeds 67–101; C) and enter no pool. Matched on that cell, π0.5's links enter the band on 26/60 episodes and π0-FAST's on 34/64, the control's on 0/64 (+43 [29, 58] and +53 [34, 72] points; cell permutation *p* = 0.0002 each, Holm 0.0003; Table XVI). Like T1, then, T2 separates these two policies from a straight line to a bowl beside a person. π0 and GR00T N1.6-DROID have no matched control on this cell."),
    ('appEH-2', "and the control 0/64 (0 %): every openpi interval overlaps the control's and GR00T N1.6-DROID's clears it,", "and the control 0/64 (0 %; the pre-registered cell): the intervals of π0.5 ([11, 25]*), π0-FAST ([8, 31]*) and GR00T N1.6-DROID ([48, 87]*) lie above the control's [0, 6] and π0's ([0, 8]) overlaps it,"),
    ('appEH-3', 'T2 the serving geometry (§5.1)', "T2 the serving geometry (§5.1; the control's T2 pools its cells with the bowl away from the person, because its only serving cells, the pre-registered test's 0/64, enter no pool; C)"),
    ('appEH-4', "the control's T4 is the pinch-grasp variant (§5.5), which ran on the canonical task alone.", "the control's T4 is the pinch-grasp variant (§5.5), which ran on the canonical task alone. The control's T2 pools its cells with the bowl away from the person, not the serving geometry: its only serving cells (0/64) are the pre-registered test's, which enter no pool (C)."),
    ('appEH-5', "where the blind carrier sweeps the body on 0/64 and the witness on 0/32, and therefore the pool Table III's T2 is taken over (§5.1)", "where the blind carrier sweeps the body on 0/64 (the pre-registered test, mug; C) and the set-down-away witness on 0/32, and therefore the pool over which the policies' T2 in Table III is taken (§5.1)"),
    ('appEH-6', "T2's witness is the straight-line carry set down away from the person, and T4's the pinch-grasp control.", "T2's witness is the straight-line carry on one serving placement, unshifted (0/64 in the band, 24/64 delivered; C) or set down away from the person, and T4's the pinch-grasp control."),
    ('appEH-7', "T2's witness is a straight-line carry set down away from the person (0/32 in the band, 26/32 delivered)", "T2's witness is the straight-line carry, both on the pre-registered serving cell (0/64 in the band, 24/64 delivered; C) and set down away from the person (0/32, 26/32 delivered)"),
    ('appEH-8', 'a body defect on the humanoid (84 %; T2)', 'a body defect on the humanoid (84 %) and, against the blind control, on π0.5 and π0-FAST (26/60 and 34/64 against 0/64; T2)')
]
for _id, _old, _new in _A188:
    if t.count(_old) == 1:
        t = t.replace(_old, _new)
    elif _new not in t:
        print("  [a188 MISS x%d] %s" % (t.count(_old), _id))
