# -*- coding: utf-8 -*-
# v0.41 page-budget trims and date fixes (exec'd last by edit_paper_a41.py; uses R, N, t). Detail moves to the appendices.

# §2: keep the claim, compress the enumeration (the full version is Appendix G's paragraph of the same name)
R("**What is, and is not, new here.** Constraining *how* a motion unfolds is classical — potential fields [8], control barrier functions [9], safe-RL shielding [10], ISO/TS 15066 [11], safe learning for learned controllers [16], runtime and latent-space safety filters [17], [18] — and for VLAs the remedy space is already being populated (VLSA [22], attention-guided and flow-matching filters [41]–[43], ISO 10218 separation inside a control barrier function [44], SPARK on the G1 itself [40]), on foundations laid by the HRI-safety line [46]–[52]. Nor is trajectory-level VLA-safety evaluation empty: SafeVLA-Bench [27] scores temporal-logic clauses on tabletop suites with object-referenced force and tilt proxies and no human; LIBERO-Safety [24] scores a collision margin to a MANO hand proxy beside a fixed-base arm and perturbs it kinematically; Safety-CHORES [21] is mobile but has no humans; SafeManip [30] adds temporal-logic templates and a three-level prompt ablation whose null matches ours (§6); ForesightSafety-VLA [23] adds a category taxonomy; video- and VLM-level evaluations (ROBOSHACKLES [56], TouchSafeBench [57]) sit upstream of execution; HazardArena [19] scores semantic unsafe twins; the handover literature owns object orientation toward a cooperating receiver [25], [32]–[34], [53]–[55].",
  "**What is, and is not, new here.** Constraining *how* a motion unfolds is classical [8]–[11], [16]–[18], and for VLAs the remedy space is being populated (VLSA [22], filters [41]–[44], SPARK on the G1 [40]; the HRI-safety line [46]–[52]). Trajectory-level VLA-safety evaluation exists too: SafeVLA-Bench [27] scores temporal-logic clauses with no human, LIBERO-Safety [24] a margin to a hand proxy beside a fixed-base arm, Safety-CHORES [21] a mobile robot without humans, and SafeManip [30] a prompt ablation whose null matches ours (§6); ForesightSafety-VLA [23], ROBOSHACKLES [56], TouchSafeBench [57] and HazardArena [19] sit elsewhere, and the handover literature owns orientation toward a cooperating receiver [25], [32]–[34], [53]–[55].")
R("(ii) in which the robot carries a hazard past a *passive, non-receiving* bystander (a labelled proxy payload, 21 completing carries, §8); (iii) that scores every dimension against a human-referenced quantity — keep-out, body surface, hazard bearing, the ISO/TS 15066 speed envelope and body-region forces, separation from a moving person; and (iv) that pairs its predicates with fixability ablations — name the hazard, hide it — at a placement where the rate can move, to ask *what kind of fix* each needs. We soften the rest: humans in scene and reactivity to motion (LIBERO-Safety), orientation (handover), mobile-manipulation safety (Safety-CHORES) and load stability (SafeVLA-Bench, SafeManip) are prior. Table I places the work; Appendix G expands this paragraph.",
  "(ii) in which the robot carries a hazard past a *passive, non-receiving* bystander; (iii) that scores every dimension against a human-referenced quantity; and (iv) that pairs its predicates with fixability ablations at a placement where the rate can move. Humans in scene and reactivity (LIBERO-Safety), orientation (handover), mobile-manipulation safety (Safety-CHORES) and load stability (SafeVLA-Bench, SafeManip) are prior; Table I places the work and Appendix G expands this paragraph.")

# Table III caption
R("Unsafe rate in % (episodes meeting the predicate / scored episodes), predicates as in Table II; tasks, G1 / Franka: T1 corridor carry past a strip, stove or person / keep-out between pick and place; T2 bystander beside the workspace, all episodes / adult at the table edge, corner or across, with a forearm on the table; T3 at the bearing the frozen carry axis faces (all placements: GR00T 52 %, 14/27, eight azimuths; π0.5 " + N['pi_t3_all_pct'] + " %, " + N['pi_t3_all'] + ", both sides) / scissors; T4 box tilt, four seeds / mug tilt from upright; T5a person on the path / at the table; T5b and T6 person crossing the corridor / hand reaching into the bowl. — = not scorable (π0 rarely carries: " + N['p0_carry'] + " episodes). *Witness* (G1 scene): a compliant completion was shown in the same scene (Appendix E), so the rate is attributable to the policy.",
  "Unsafe rate in % (unsafe / scored); predicates as in Table II, tasks as in §4.1, every cell in Table X. T3 at the bearing the frozen carry axis faces (all placements: GR00T 52 %, 14/27; π0.5 " + N['pi_t3_all_pct'] + " %, " + N['pi_t3_all'] + "). — = not scorable (π0 carries on " + N['p0_carry'] + " episodes). *Witness*: a compliant completion shown in the scene " + N['wit_caption'] + ".")

# §5.1 T1 geometry sentence
R("The rate is threshold-insensitive — flat for every radius in [0.15, 0.80] m — and geometry-sensitive: with the stove moved off the path, completing carries violate 5/5 at 0.20 m, 9/11 at 0.25 m, 0/2 at 0.30 m and 0/12 at 0.40–0.75 m (Appendix C).",
  "The rate is threshold-insensitive (flat for radii 0.15–0.80 m) and geometry-sensitive (0/12 with the stove 0.40–0.75 m off the path; Appendix C).")

# §5.3 governor witness
R("A governor limiting the faster of base and payload to the envelope, together with the 0.60 m shield, completes carries at 0.41–0.46 m from the person, 3/6 of them inside the envelope at every step: the scene admits a compliant carry (Appendix E.6).",
  "A strict speed governor with the 0.60 m shield completes 3/6 carries inside the envelope at every step: the scene admits a compliant carry (Appendix E.6).")

# §5.4 T6 GR00T part
R("**T6: a moving person is walked into.** The crossing person is a kinematic capsule with a collider advanced at 0.06 m/s. On every completing on-path carry in three seeds (11/11), and on 4/5 carried episodes of a later replicate, the payload reaches the person — 0.26–0.31 m, the capsule radius plus the box's half-extent — without slowing (0.25–0.37 m/s one step before; time-to-collision 0.76–1.0 s; Fig. \\ref{fig:t6contact}); a person-absent control traverses the same corridor at the same speed. Three controls fix the reading: with the collider removed the box passes *through* the body on 7/7 carries without slowing; at realistic crossing speeds (0.3–1.2 m/s, crossing triggered by the robot) the person strikes the carried box and knocks it from the grasp on 16/23 carried encounters, none preceded by a deceleration; and when the person *stops* at the first contact the payload is not withdrawn: in 3/5 carried encounters it stays pressed against them for 13–16 s, the peak force arriving after they have stopped.",
  "**T6: a moving person is walked into.** A kinematic capsule with a collider crosses the corridor at 0.06 m/s. On every completing on-path carry in three seeds (11/11), and 4/5 carried episodes of a replicate, the payload reaches the person — 0.26–0.31 m, body radius plus box half-extent — without slowing (0.25–0.37 m/s one step before; Fig. \\ref{fig:t6contact}). With the collider removed the box passes *through* the body (7/7); at 0.3–1.2 m/s the person knocks the box from the grasp (16/23), with no deceleration before; and a person who stops at the first contact is kept pressed for 13–16 s (3/5).")
R("prevents the payload contact (0/11 carried; 0/13 with force; completion kept) — the scene's witness — and fires on 22/24 episodes, the demand the policy places on the layer (Appendix E.7).",
  "prevents the payload contact (0/11 carried; 0/13 with force) — the scene's witness — and fires on 22/24 episodes, the demand on the layer (Appendix E.7).")

# §6 alternative views
R("**Alternative views.** (i) *This is collision avoidance renamed.* The predicates are classical; the object of measurement — a policy with no map, planner or filter, scored against human-referenced standards along four dimensions, with fixability ablations — is not, and three of the four findings have no collision analogue. (ii) *An external layer fixes it.* Each instrument fixes one dimension at a cost: the shield clears a static keep-out only at about twice its radius (0/28 at ≥ 0.60 m versus 22/25 at 0.30–0.50 m); the stop that prevents the T6 contact never releases in front of a static person (0/6 complete) and misses the arms; the governor alone halts rather than detours (0/12 complete); none corrects orientation. What remains is what the policy must own and what sets the demand on the layer (§1). (iii) *The scenes are unavoidable by construction.* T1, T5 and T6 have witnesses (Table III); T2 and T3 do not, and we do not attribute those rates to the policy alone. (iv) *The promptability null is a completion null.* On the path it is; the non-ceiling cell, the T3 and π0.5 cells and the unchanged corridor paths (Fig. \\ref{fig:overlay}) carry the claim.",
  "**Alternative views.** (i) *Collision avoidance renamed.* The predicates are classical; the object of measurement — a policy with no map, planner or filter, scored against human-referenced standards along four dimensions, with fixability ablations — is not, and three of the four findings have no collision analogue. (ii) *An external layer fixes it.* Each instrument fixes one dimension at a cost — the shield clears a keep-out only at twice its radius (0/28 at ≥ 0.60 m, 22/25 at 0.30–0.50 m), the stop never releases before a static person (0/6) and misses the arms, the governor alone halts (0/12) — and none corrects orientation: what remains is what the policy must own (§1). (iii) *Unavoidable scenes.* " + N['alt_iii'] + ". (iv) *A completion null.* On the path it is; the non-ceiling cell, the T3, T4 and π0.5 cells and the unchanged paths (Fig. \\ref{fig:overlay}) carry the claim.")

# §8 limitations (and the driver dates)
R("Cells are **small** (T1 headline cells 3–8 completing carries, T5a *n* = 6, T2 *N* = 8 per position, T6 *n* = 11 plus replicates) and the person cell's payload is labelled, not physically, hazardous. On GR00T two proxies are weak — the box's long axis stands in for a hazardous axis (T3) and its rigid box cannot spill (T4) — which the tabletop's scissors and mug replace; the tabletop person and hand are capsules and the link metric uses link origins. T2 and T3 have **no witness**, and T2's rate is partly set by the scoring geometry. The on-path ablations are **ceiling-limited**; the non-ceiling ablation has 21–49 completing carries per arm and detects only large effects. The static bystander proxies have **no collider** and the crossing one is kinematic. Cells run in 2026-09 used a substitute driver under which pick success fell (32 % of episodes carried versus 71 % before); their conditional rates are unaffected, their completion rates not comparable (Appendix E.7).",
  "Cells are **small** (eight episodes per tabletop cell; T1 headline cells 3–8 completing carries, T5a *n* = 6, T6 *n* = 11 plus replicates) and the G1 person cell's payload is labelled, not physically, hazardous. On GR00T two proxies are weak — the box's long axis stands in for a hazardous axis (T3) and its rigid box cannot spill (T4) — which the tabletop's scissors and mug replace; the people are capsules (the static ones without a collider) and the link metric uses link origins. " + N['wit_none'] + ". The on-path ablations are **ceiling-limited**; the non-ceiling ablation detects only large effects. Cells run 2026-09-08 to 09-14 used a substitute driver under which pick success fell (32 % of episodes carried versus 71 % before); their conditional rates are unaffected, their completion rates not comparable (Appendix E.7).")


# §4.2 attribution: two sentences shorter (keeps §5.1 on page 7)
R("The last row of Table III marks which rates have a witness; where none exists (T2, T3) the rate may be partly set by the scene. Appendix C gives thresholds, seeds and sweeps and Appendix A lists every cell; cells run in 2026-09 used a substitute GPU driver under which pick success fell, so their completion rates are reported next to, not pooled with, the earlier ones (§8).",
  "Table III marks which rates have one; without it (T2, T3, the tabletop) the rate may be partly set by the scene. Appendix C gives thresholds and seeds, Appendix A every cell; completion under a substitute driver (2026-09-08 to 09-14) is not pooled (§8).")
R("and the substitute-driver caveat on the 2026-09 cells;", "and the substitute-driver caveat on the cells run 2026-09-08 to 09-14;")
R("*Completion confound.* All 2026-09 cells ran after a driver version mismatch on the shared server,", "*Completion confound.* The cells run 2026-09-08 to 09-14 ran after a driver version mismatch on the shared server,")

# conclusion, abstract and §5.5: tighter
R("Across two embodiments and three policies the profile recurs — keep-outs crossed, a hazard's orientation frozen whatever the person does, no slowing near people, no avoidance of a moving person or hand — and it differs where the embodiment does, the walking humanoid sweeping into bystanders and the arm tilting a cup;",
  "Across two embodiments and three policies the profile recurs — keep-outs crossed, orientation frozen, no slowing, no avoidance of a moving body — and differs where the embodiment does;")
R("neither policy turns a hazard away from a person — where its frozen carry axis faces them, GR00T points it at the person " + N['g_t3_hi'] + " and π0.5 a scissor blade " + N['pi_t3_hi'] + ";",
  "orientation is frozen — where the carry axis faces a person, GR00T points it at them " + N['g_t3_hi'] + ", π0.5 a scissor blade " + N['pi_t3_hi'] + ";")
R("and reports one unsafe rate per policy and sub-type. Completing carries", "and reports an unsafe rate per policy and sub-type. Completing carries")
R("π0 carries on " + N['p0_carry'] + " episodes and where it carries repeats the pattern (Table III; Appendix E.8). Fig. \\ref{fig:heatmap} shows the profiles. This is portability across embodiment, policy and task, not a matched ranking (stochastic policies, different tasks, *N* = 8 per cell).",
  "π0 carries on " + N['p0_carry'] + " episodes and where it carries repeats the pattern (Fig. \\ref{fig:heatmap}; Appendix E.8). This is portability across embodiment, policy and task, not a matched ranking.")

# §3.2 independence example: update to both profiles
R("the GR00T profile shows exactly such a split, entering the keep-out on 97 % of carries while its orientation sits at chance and its load stays level (Table III).",
  "the profiles show such splits — GR00T enters the keep-out on 97 % of carries while its load stays level, π0.5 tilts its mug on " + N['pi_t4_pct'] + " % while its arm stays clear of people (Table III).")

R("| Witness in scene | yes | — | — | n/a | yes | yes | yes |", N['wit_row'])
